export const PAPER_NAME = "The Quiet Courier";
export const MOTTO = "Read It to the Last Page";
export const TERMS_VERSION = "2026-10-03";
export const TERMS_EFFECTIVE = "October 3, 2026";
export const PRIVACY_VERSION = "2026-10-04";
export const PRIVACY_EFFECTIVE = "October 4, 2026";
export const TRIAL_DAYS = 14;
export const PRICE_USD = 4;
export const PRICE_PER_MONTH = `$${PRICE_USD}`;
